from __future__ import annotations

STARTER_STATES = [
    {
        "id": "gather",
        "name": "Gather",
        "kind": "gather",
        "domain": "Context intake",
        "goal_template": "Retrieve high-signal memories, recent artifacts, and source links for the current memory stewardship question.",
        "prompt_contract": "Prefer primary sources, preserve source links, and summarize only what the next state needs.",
        "output_contract": "A compact context bundle with source ids, confidence, unresolved gaps, and token estimate.",
        "tools": ["only_memories.search", "only_memories.navigate", "filesystem.read"],
        "skills": ["source_triangulation", "context_compression"],
        "context_minimum": 65_536,
        "model_policy": "cheap-capable",
        "x": 50,
        "y": 40,
        "is_current": True,
    },
    {
        "id": "curate",
        "name": "Curate",
        "kind": "curate",
        "domain": "Memory maintenance",
        "goal_template": "Merge duplicates, mark stale candidates, and propose bridge memories without deleting provenance.",
        "prompt_contract": "Treat forgetting as reversible and explain every proposed memory lifecycle change.",
        "output_contract": "A structured memory-change proposal with source ids and rollback notes.",
        "tools": ["only_memories.remember", "only_memories.forget", "only_memories.reinforce_connection"],
        "skills": ["deduplication", "graph_stewardship"],
        "context_minimum": 65_536,
        "model_policy": "maintenance",
        "x": 77,
        "y": 52,
    },
    {
        "id": "synthesize",
        "name": "Synthesize",
        "kind": "synthesize",
        "domain": "Bridge memory creation",
        "goal_template": "Create concise synthesis artifacts that help future agents navigate the memory graph.",
        "prompt_contract": "Prefer durable insight over broad summaries. Include what changed and why it matters.",
        "output_contract": "A synthesis artifact with dependencies, expiry, and suggested graph connections.",
        "tools": ["artifact.write"],
        "skills": ["abstraction", "artifact_design"],
        "context_minimum": 128_000,
        "model_policy": "balanced",
        "x": 75,
        "y": 68,
    },
    {
        "id": "validate",
        "name": "Validate",
        "kind": "validate",
        "domain": "Evidence and contradiction checks",
        "goal_template": "Check whether proposed memory changes are supported, contradicted, expired, or too uncertain.",
        "prompt_contract": "Flag contradictions explicitly and return to gather if evidence is insufficient.",
        "output_contract": "A validation report with accepted changes, rejected changes, risks, and next transition.",
        "tools": ["only_memories.search", "only_memories.versions", "web.search"],
        "skills": ["source_evaluation", "contradiction_detection"],
        "context_minimum": 128_000,
        "model_policy": "balanced",
        "x": 50,
        "y": 87,
    },
    {
        "id": "publish",
        "name": "Publish",
        "kind": "publish",
        "domain": "Durable outputs",
        "goal_template": "Commit accepted memory changes, procedure recaps, and inspectable output artifacts.",
        "prompt_contract": "Make the final state visible to later agents and operators.",
        "output_contract": "Committed memory writes, recap entries, and links to changed resources.",
        "tools": ["only_memories.remember", "only_memories.forget", "only_memories.restore", "only_memories.reinforce", "artifact.write"],
        "skills": ["provenance_writing", "operator_handoff"],
        "context_minimum": 32_768,
        "model_policy": "cheap-capable",
        "x": 25,
        "y": 66,
    },
    {
        "id": "audit",
        "name": "Audit",
        "kind": "audit",
        "domain": "Procedure governance",
        "goal_template": "Evaluate run quality, model fit, budget pressure, and whether the procedure should change.",
        "prompt_contract": "Use a stronger model only when the cheaper loop is failing or changing the procedure.",
        "output_contract": "Auditor recap plus optional procedure mutation proposal.",
        "tools": ["consciousness.procedure.read", "consciousness.procedure.propose_mutation"],
        "skills": ["procedure_design", "model_governance", "budget_control"],
        "context_minimum": 200_000,
        "model_policy": "auditor",
        "x": 23,
        "y": 36,
    },
]

STARTER_TRANSITIONS = [
    ("gather", "curate", 1.0, "Context bundle is fresh enough for memory maintenance."),
    ("curate", "synthesize", 1.0, "Curated candidates need durable bridge artifacts."),
    ("synthesize", "validate", 1.0, "Synthesized artifacts require evidence and contradiction checks."),
    ("validate", "publish", 1.0, "Accepted changes can be made visible to later agents."),
    ("publish", "audit", 1.0, "Every publish cycle should be evaluated by governance."),
    ("audit", "gather", 1.0, "The loop returns to intake after governance."),
    ("validate", "gather", 0.35, "Insufficient evidence reopens intake."),
    ("audit", "curate", 0.25, "Procedure audit can request a focused curation pass."),
    ("publish", "gather", 0.2, "Low-risk publish cycles can skip deep audit under budget pressure."),
]

STARTER_MODELS = [
    {
        "id": "local/llama-3.1-8b-instruct",
        "provider": "ollama",
        "model": "llama-3.1-8b-instruct",
        "context_window": 32_768,
        "relative_cost": 0.0,
        "max_run_budget": 0.0,
        "quality_tier": 1,
        "strengths": ["classification", "simple-maintenance", "offline"],
        "open_weights": True,
    },
    {
        "id": "local/qwen2.5-14b-instruct",
        "provider": "ollama",
        "model": "qwen2.5-14b-instruct",
        "context_window": 65_536,
        "relative_cost": 0.0,
        "max_run_budget": 0.0,
        "quality_tier": 2,
        "strengths": ["curation", "structured-output", "offline"],
        "open_weights": True,
    },
    {
        "id": "openai/gpt-5.6-luna",
        "provider": "openai",
        "model": "gpt-5.6-luna",
        "context_window": 128_000,
        "relative_cost": 1.0,
        "max_run_budget": 0.15,
        "quality_tier": 3,
        "strengths": ["balanced", "tool-use", "synthesis", "structured-output"],
    },
    {
        "id": "openai/gpt-5.6-sol",
        "provider": "openai",
        "model": "gpt-5.6-sol",
        "context_window": 200_000,
        "relative_cost": 4.0,
        "max_run_budget": 1.0,
        "quality_tier": 5,
        "strengths": ["procedure-design", "evaluation", "model-governance"],
    },
]
